package cn.ysf.ydma.dao;

import cn.ysf.ydma.entity.Course;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    @Delete({
        "delete from course",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    @Insert({
        "insert into course (id, name, ",
        "intro, learn_count, ",
        "difficulty, score, ",
        "image, publish_time, ",
        "price, subject_id, ",
        "direction_id, learn_time)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{intro,jdbcType=VARCHAR}, #{learnCount,jdbcType=INTEGER}, ",
        "#{difficulty,jdbcType=VARCHAR}, #{score,jdbcType=INTEGER}, ",
        "#{image,jdbcType=VARCHAR}, #{publishTime,jdbcType=TIMESTAMP}, ",
        "#{price,jdbcType=INTEGER}, #{subjectId,jdbcType=INTEGER}, ",
        "#{directionId,jdbcType=INTEGER}, #{learnTime,jdbcType=INTEGER})"
    })
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    @InsertProvider(type=CourseSqlProvider.class, method="insertSelective")
    int insertSelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    @Select({
        "select",
        "id, name, intro, learn_count, difficulty, score, image, publish_time, price, ",
        "subject_id, direction_id, learn_time",
        "from course",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="intro", property="intro", jdbcType=JdbcType.VARCHAR),
        @Result(column="learn_count", property="learnCount", jdbcType=JdbcType.INTEGER),
        @Result(column="difficulty", property="difficulty", jdbcType=JdbcType.VARCHAR),
        @Result(column="score", property="score", jdbcType=JdbcType.INTEGER),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish_time", property="publishTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="subject_id", property="subjectId", jdbcType=JdbcType.INTEGER),
        @Result(column="direction_id", property="directionId", jdbcType=JdbcType.INTEGER),
        @Result(column="learn_time", property="learnTime", jdbcType=JdbcType.INTEGER)
    })
    Course selectByPrimaryKey(Integer id);
/**通过**/
@Select({
        "select",
        "id, name, intro, learn_count, difficulty, score, image, publish_time, price, ",
        "subject_id, direction_id, learn_time",
        "from course",
        "where subject_id = #{id,jdbcType=INTEGER}"
})
@Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="intro", property="intro", jdbcType=JdbcType.VARCHAR),
        @Result(column="learn_count", property="learnCount", jdbcType=JdbcType.INTEGER),
        @Result(column="difficulty", property="difficulty", jdbcType=JdbcType.VARCHAR),
        @Result(column="score", property="score", jdbcType=JdbcType.INTEGER),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="publish_time", property="publishTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
        @Result(column="subject_id", property="subjectId", jdbcType=JdbcType.INTEGER),
        @Result(column="direction_id", property="directionId", jdbcType=JdbcType.INTEGER),
        @Result(column="learn_time", property="learnTime", jdbcType=JdbcType.INTEGER)
})
    List<Course> selectBySubject_id(Integer id);

    @Select({
            "select",
            "id, name, intro, learn_count, difficulty, score, image, publish_time, price, ",
            "subject_id, direction_id, learn_time",
            "from course",
            "where direction_id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="intro", property="intro", jdbcType=JdbcType.VARCHAR),
            @Result(column="learn_count", property="learnCount", jdbcType=JdbcType.INTEGER),
            @Result(column="difficulty", property="difficulty", jdbcType=JdbcType.VARCHAR),
            @Result(column="score", property="score", jdbcType=JdbcType.INTEGER),
            @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
            @Result(column="publish_time", property="publishTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="price", property="price", jdbcType=JdbcType.INTEGER),
            @Result(column="subject_id", property="subjectId", jdbcType=JdbcType.INTEGER),
            @Result(column="direction_id", property="directionId", jdbcType=JdbcType.INTEGER),
            @Result(column="learn_time", property="learnTime", jdbcType=JdbcType.INTEGER)
    })
    List<Course> selectByDirection_id(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    @UpdateProvider(type=CourseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    @Update({
        "update course",
        "set name = #{name,jdbcType=VARCHAR},",
          "intro = #{intro,jdbcType=VARCHAR},",
          "learn_count = #{learnCount,jdbcType=INTEGER},",
          "difficulty = #{difficulty,jdbcType=VARCHAR},",
          "score = #{score,jdbcType=INTEGER},",
          "image = #{image,jdbcType=VARCHAR},",
          "publish_time = #{publishTime,jdbcType=TIMESTAMP},",
          "price = #{price,jdbcType=INTEGER},",
          "subject_id = #{subjectId,jdbcType=INTEGER},",
          "direction_id = #{directionId,jdbcType=INTEGER},",
          "learn_time = #{learnTime,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Course record);
}