package cn.ysf.ydma.entity;

import java.io.Serializable;
import java.util.Date;

public class Course implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.intro
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.learn_count
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer learnCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.difficulty
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private String difficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.score
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.image
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.publish_time
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.subject_id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.direction_id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer directionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.learn_time
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    private Integer learnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.intro
     *
     * @return the value of course.intro
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.intro
     *
     * @param intro the value for course.intro
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.learn_count
     *
     * @return the value of course.learn_count
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getLearnCount() {
        return learnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.learn_count
     *
     * @param learnCount the value for course.learn_count
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setLearnCount(Integer learnCount) {
        this.learnCount = learnCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.difficulty
     *
     * @return the value of course.difficulty
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public String getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.difficulty
     *
     * @param difficulty the value for course.difficulty
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty == null ? null : difficulty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.score
     *
     * @return the value of course.score
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.score
     *
     * @param score the value for course.score
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.image
     *
     * @return the value of course.image
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.image
     *
     * @param image the value for course.image
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.publish_time
     *
     * @return the value of course.publish_time
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.publish_time
     *
     * @param publishTime the value for course.publish_time
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.subject_id
     *
     * @return the value of course.subject_id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.subject_id
     *
     * @param subjectId the value for course.subject_id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.direction_id
     *
     * @return the value of course.direction_id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getDirectionId() {
        return directionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.direction_id
     *
     * @param directionId the value for course.direction_id
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setDirectionId(Integer directionId) {
        this.directionId = directionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.learn_time
     *
     * @return the value of course.learn_time
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public Integer getLearnTime() {
        return learnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.learn_time
     *
     * @param learnTime the value for course.learn_time
     *
     * @mbg.generated Wed Apr 29 16:26:59 CST 2020
     */
    public void setLearnTime(Integer learnTime) {
        this.learnTime = learnTime;
    }
}