package cn.ysf.ydma.dao;

import cn.ysf.ydma.entity.Subject;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Apr 29 18:56:24 CST 2020
     */
    @Delete({
        "delete from subject",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Apr 29 18:56:24 CST 2020
     */
    @Insert({
        "insert into subject (id, name, ",
        "direction_id)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{directionId,jdbcType=INTEGER})"
    })
    int insert(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Apr 29 18:56:24 CST 2020
     */
    @InsertProvider(type=SubjectSqlProvider.class, method="insertSelective")
    int insertSelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Apr 29 18:56:24 CST 2020
     */
    @Select({
        "select",
        "id, name, direction_id",
        "from subject",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="direction_id", property="directionId", jdbcType=JdbcType.INTEGER)
    })
    Subject selectByPrimaryKey(Integer id);
    /**Mybatis关联表查询**/
    @Select({
            "select",
            "id, name, direction_id",
            "from subject",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="direction_id", property="directionId", jdbcType=JdbcType.INTEGER),
            @Result(column ="direction_id",property = "direction",
            one=@One(select = "cn.ysf.ydma.dao.DirectionMapper.selectByPrimaryKey"))
    })
    Subject selectById(Integer id);
    @Select({
            "select",
            "id, name, direction_id",
            "from subject",
            "where direction_id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
            @Result(column="direction_id", property="directionId", jdbcType=JdbcType.INTEGER)
    })
    List<Subject> selectByDirectionId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Apr 29 18:56:24 CST 2020
     */
    @UpdateProvider(type=SubjectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subject
     *
     * @mbg.generated Wed Apr 29 18:56:24 CST 2020
     */
    @Update({
        "update subject",
        "set name = #{name,jdbcType=VARCHAR},",
          "direction_id = #{directionId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Subject record);
}