package cn.ysf.ydma.entity;

import java.util.List;

public class Direction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.id
     *
     * @mbg.generated Wed Apr 29 16:28:46 CST 2020
     */
    private Integer id;

    public List getCourses() {
        return courses;
    }

    public void setCourses(List courses) {
        this.courses = courses;
    }

    private List courses;

    @Override
    public String toString() {
        return "Direction{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", subjects=" + subjects +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.name
     *
     * @mbg.generated Wed Apr 29 16:28:46 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direction.id
     *
     * @return the value of direction.id
     *
     * @mbg.generated Wed Apr 29 16:28:46 CST 2020
     */
    private List<Subject> subjects;

    public Direction(Integer id, String name, List<Subject> subjects) {
        this.id = id;
        this.name = name;
        this.subjects = subjects;
    }

    public Direction() {
    }

    public void setSubjects(List<Subject> subjects) {
        this.subjects = subjects;
    }

    public List<Subject> getSubjects() {
        return subjects;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direction.id
     *
     * @param id the value for direction.id
     *
     * @mbg.generated Wed Apr 29 16:28:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direction.name
     *
     * @return the value of direction.name
     *
     * @mbg.generated Wed Apr 29 16:28:46 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direction.name
     *
     * @param name the value for direction.name
     *
     * @mbg.generated Wed Apr 29 16:28:46 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}